Only turn on autocomplete.js if `WHOOGLE_AUTOCOMPLETE` is enabled.
benbusby/whoogle-search pull request #611
Opened 2022-01-14 02:29 UTC by DUOLabs333

2022-01-14 02:30 UTC, DUOLabs333 commented
Should fix #610

2022-01-14 16:56 UTC, benbusby requested changes
The treatment of this environment variable needs to be inverted. `WHOOGLE_AUTOCOMPLETE` should only ever used to disable the feature. I'd rather not have an entire feature suddenly disappear for the majority of users who are accustomed to it being enabled by default.

2022-01-14 16:58 UTC, DUOLabs333 commented
But it is -- if it doesn't exist, it is 1 by default.

2022-01-14 17:00 UTC, benbusby commented
Ah I see. The title of the PR threw me off and I hadn't looked at the code much yet. Will review now.

2022-01-14 17:08 UTC, benbusby requested changes
Looks good, just a couple minor formatting fixes before I merge.

2022-01-14 17:08 UTC, benbusby commented on app/routes.py
> +autocomplete_enabled=os.getenv(ac_var,'1')
pep8 fixes:

```suggestion
ac_var = 'WHOOGLE_AUTOCOMPLETE'
autocomplete_enabled = os.getenv(ac_var, '1')
```

2022-01-14 17:08 UTC, benbusby commented on app/templates/display.html
> +    {% endif %}
Indentation issue
```suggestion
{% if autocomplete_enabled == '1' %}
    <script src="{{ cb_url('autocomplete.js') }}"></script>
{% endif %}
```

2022-01-14 17:13 UTC, benbusby commented on app/routes.py
> +autocomplete_enabled = os.getenv(ac_var, '1')
pep8 also enforces 2 line breaks before function defs

```suggestion
autocomplete_enabled = os.getenv(ac_var, '1')

```

2022-01-18 15:48 UTC, DUOLabs333 commented
So, is it ready to be merged?

2022-01-18 20:38 UTC, benbusby approved these changes

2022-01-18 20:39 UTC, merged